CREATE DATABASE IF NOT EXISTS `PHPMVC`;
CREATE TABLE IF NOT EXISTS `PHPMVC`.`users` (
    `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(255) NOT NULL,
    `first_name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL
);